baseURL = "https://ruitcatarino.github.io/"
title = "CodeMemoirs"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[pagination]
  pagerSize = 3

[Params.author]
  name = "Rui Catarino"
  abstract = """
  A software engineer working as a backend developer who loves to code and learn new things.
  """
  github = "https://github.com/ruitcatarino/"
  linkedin = "https://www.linkedin.com/in/ruitcatarino/"
  medium = "https://medium.com/@ruitcatarino/"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "paraiso-dark"

[Params]
  darkmode = true
